export const assets = {
  logo: '/assets/gno-logo-banner.png',
  logoIcon: '/assets/gno-logo-banner.png',
  logoWhite: '/assets/gno-logo-white.png',
  logoNavbar: '/assets/gno-logo-black.png',
  logoBanner: '/assets/gno-logo-banner.png',
  heroFamily: '/assets/gno-hero-main.png',
  heroDesign: '/assets/gno-hero-facility.png',
  lifestyleGaming: '/assets/gno-lifestyle-field.png',
  lifestyleFamily: '/assets/gno-lifestyle-logistics.png',
  product1: '/assets/gno-product-lubricant.png',
  product2: '/assets/gno-product-merch.png',
  product3: '/assets/gno-product-safety.png',
  productHydraulic: '/assets/gno-product-hydraulic.png',
  productCap: '/assets/gno-product-cap.png',
  productBundle: '/assets/gno-product-bundle.png',
  icon1: '/assets/gno-icon-drop.svg',
  icon2: '/assets/gno-icon-energy.svg',
  icon3: '/assets/gno-icon-shipping.svg',
} as const
